stages: 
    - test

test:qa:
    stage: test
    rules:
        - if: '$CI_COMMIT_TAG =~ /^[qQ][aA]-/'
    script:
        - "echo -e \"It from qa-*\""

test:other:
    stage: test
    rules:
      - if: '$CI_COMMIT_BRANCH == "devel"'
    script:
        - "echo -e \"It from NOT qa-*\""
