stages: 
    - test

test:1:
    stage: test
    rules:
        - if: '$CI_COMMIT_TAG =~ /^[qQ][aA]-/'
    script:
        - "echo -e \"It from qa-*\""

test:2:
    stage: test
    except: 
      - main
      - /^[qQ][aA]-/
    script:
        - "echo -e \"It from not qa-*\""
